array_layout = "Block"
chain_indent = "Block"
closure_block_indent_threshold = -1
condense_wildcard_suffices = true
fn_args_layout = "Block"
fn_call_style = "Block"
fn_call_width = 80
max_width = 80
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
struct_lit_style = "Block"
tab_spaces = 2
